export { default as HeroSection } from './HeroSection';
export { default as AboutSection } from './AboutSection';
export { default as ProgramSection } from './ProgramSection';
export { default as ScheduleSection } from './ScheduleSection';
export { default as InstructorsSection } from './InstructorsSection';
export { default as LocationSection } from './LocationSection';
export { default as PricingSection } from './PricingSection';
export { default as FAQSection } from './FAQSection';
export { default as ContactSection } from './ContactSection'; 